### ISSUE TITLE
Remove `nodejs` from `run` dependency

### ISSUE THREAD

**Issue by fcollonval** [conda-forge/jupyterlab-git-feedstock#1]
Dear maintainers,

Is there a particular reason why `nodejs` is a `run` dependency of this package?

https://github.com/conda-forge/jupyterlab-git-feedstock/blob/f09d8fb70bd711225ea6eb309241d7ea0e228342/recipe/meta.yaml#L25-L30

In use case where administrators don't want users to add jupyterlab extensions, a solution is to ship JupyterLab with prepackaged extensions and without nodeJS. Therefore it would be nice to remove it from this great extension.

**Comment by dbast** [comment]
@fcollonval Thanks for bringing that up. Doing that differently is not that easy. Ideas are welcome.

Current procedure is:
* the package is build via `"${PREFIX}/bin/jupyter" labextension install . --no-build`
* when jupyterlab is started, it asks for doing a `rebuild`, which can be just confirmed and is then done in the backround. This is also documented here https://jupyterlab.readthedocs.io/en/stable/user/extensions.html 

If you remove that `--no-build` or do a `jupyter lab build` as part of the build precess and include the result to not require nodejs as run dependency, it has the following consequences:
* jupyterlab still wants to rebuild on startup -> nodejs required, meaning packaging the prebuild files was not successful
* the package gets quit huge... >30 MByte with >10k files.

Any different idea welcome.

**Comment by fcollonval** [comment]
Hey, I must admit I was in the rush of packaging a new JupyterLab with prepackaged extensions. So I have not broaden my point of view.

The most common use case for conda package manager is certainly this approach:

1. I type `conda install a_nice_jupyterlab_extension`
2. I got the front-end extension and potentially the associated back-end extension installed

This recipe will definitely fit that use case. So I will close this issue as I don't have better idea not breaking the previous use case.

I just would like to emphasize my preference for jupyterlab extensions manager use case. It has the ability to install back-end extension if needed. And for administration, that means a simple choice to activate or not the extensions manager extension.

*A note*
> the package gets quit huge... >30 MByte with >10k files.

If you run `jupyter lab clean` after `jupyter lab build` the `staging` folder will be removed keeping only the final jupyterlab build in `static` (the package will still be about 10-15MBytes).  But this is not a solution as that may package a jupyterlab version not matching the user one and all other extensions will have to be reinstalled.

**Comment by fcollonval** [comment]
Reopening following #11 proposal.

**Comment by fcollonval** [comment]
nodejs is no more needed for JupyterLab 3 - closing this following #36
